/**
 * Interactive setup script for .env.local
 * Run with: node scripts/setup-env.js
 */

const fs = require('fs');
const path = require('path');
const readline = require('readline');

const rl = readline.createInterface({
  input: process.stdin,
  output: process.stdout
});

function question(prompt) {
  return new Promise((resolve) => {
    rl.question(prompt, resolve);
  });
}

async function setup() {
  console.log('🚀 TinyLink Database Setup\n');
  console.log('This script will help you create a .env.local file with your database connection.\n');

  const envPath = path.join(process.cwd(), '.env.local');
  
  // Check if .env.local already exists
  if (fs.existsSync(envPath)) {
    const overwrite = await question('⚠️  .env.local already exists. Overwrite? (y/n): ');
    if (overwrite.toLowerCase() !== 'y') {
      console.log('Setup cancelled.');
      rl.close();
      return;
    }
  }

  console.log('\n📋 Database Provider Options:');
  console.log('1. Neon (Recommended - Free PostgreSQL)');
  console.log('2. Supabase');
  console.log('3. Railway');
  console.log('4. Other (I have a connection string)\n');

  const choice = await question('Select option (1-4): ');

  let connectionString = '';

  if (choice === '1') {
    console.log('\n📝 Neon Setup Instructions:');
    console.log('1. Go to https://neon.tech and sign up');
    console.log('2. Create a new project');
    console.log('3. Copy your connection string from the dashboard\n');
    connectionString = await question('Paste your Neon connection string: ');
  } else if (choice === '2') {
    console.log('\n📝 Supabase Setup Instructions:');
    console.log('1. Go to https://supabase.com and sign up');
    console.log('2. Create a new project');
    console.log('3. Go to Settings → Database → Connection string\n');
    connectionString = await question('Paste your Supabase connection string: ');
  } else if (choice === '3') {
    console.log('\n📝 Railway Setup Instructions:');
    console.log('1. Go to https://railway.app and sign up');
    console.log('2. Create a new PostgreSQL database');
    console.log('3. Copy the connection string\n');
    connectionString = await question('Paste your Railway connection string: ');
  } else {
    console.log('\n📝 Enter your PostgreSQL connection string:');
    connectionString = await question('Connection string: ');
  }

  connectionString = connectionString.trim();

  if (!connectionString) {
    console.log('\n❌ Error: Connection string cannot be empty');
    rl.close();
    return;
  }

  // Validate it looks like a PostgreSQL connection string
  if (!connectionString.startsWith('postgresql://') && !connectionString.startsWith('postgres://')) {
    console.log('\n⚠️  Warning: Connection string should start with "postgresql://" or "postgres://"');
    const continueAnyway = await question('Continue anyway? (y/n): ');
    if (continueAnyway.toLowerCase() !== 'y') {
      console.log('Setup cancelled.');
      rl.close();
      return;
    }
  }

  // Write .env.local file
  const envContent = `# Database Connection String
# Generated by setup script
DATABASE_URL=${connectionString}
`;

  try {
    fs.writeFileSync(envPath, envContent);
    console.log('\n✅ Success! Created .env.local file');
    console.log('\n📝 Next steps:');
    console.log('1. Test your connection: npm run test-db');
    console.log('2. Start the dev server: npm run dev');
    console.log('3. Visit http://localhost:3000\n');
  } catch (error) {
    console.error('\n❌ Error creating .env.local:', error.message);
  }

  rl.close();
}

setup();


